#!/bin/bash

if [ -z $1 ]; then
   echo "Usage: maintenance (on|off|sleep NUM VALUE)"
   echo ""
   echo "Example: "
   echo ""
   echo "maintenance on - Switches on Maintenance Mode"
   echo "maintenance off - Switches off Maintenance Mode"
   echo "maintenance sleep - Switches on Maintenance Mode temporarily for 15 minutes"
   echo "maintenance sleep 10 min - Switches on Maintenance Mode temporarily for 10 min"
   echo ""
   echo "Valid VALUE is seconds (sec, secs), minutes (min, mins) , hours (hour, hr) , days (day)"
   exit
fi

case "${1,,}" in
     "on" | "true" )
        sed -i "s|include /etc/nginx/sites.enabled/\*.conf;|#include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|#include /etc/nginx/templates/maintenance.template;|include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        echo 'Maintenance Mode Activated'
     ;;
     "off" | "false" )
        sed -i "s|#include /etc/nginx/sites.enabled/\*.conf;|include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|include /etc/nginx/templates/maintenance.template;|#include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        echo 'Maintenance Mode Deactivated'
     ;;
     "sleep" | "temp" )
        sed -i "s|include /etc/nginx/sites.enabled/\*.conf;|#include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|#include /etc/nginx/templates/maintenance.template;|include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        if [ -z $2 ]; then
            sleepnum="15"
            sleepcalc=$((15 * 60))
        fi

        if [ -z $3 ]; then
            set -- "${@:1:2}" "min"
        fi

        case "${3,,}" in
            "min" | "minutes" )
                sleepcalc=$(($2 * 60))
                sleepdesc="minutes"
             ;;
             "seconds" | "secs" | "sec" )
                sleepcalc=$(($2 * 1))
                sleepdesc="seconds"
             ;;
              "hour" | "hours" | "hr" | "hrs" )
                sleepcalc=$(($2 * 3600))
                sleepdesc="hour(s)"
             ;;
             "day" | "days" )
                sleepcalc=$(($2 * 86400))
                sleepdesc="day(s)"
             ;;
        esac

        echo 'Maintenance Mode Temporarily Activated for '$sleepnum' '$sleepdesc
        sleep $sleepcalc
        sed -i "s|#include /etc/nginx/sites.enabled/\*.conf;|include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|include /etc/nginx/templates/maintenance.template;|#include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        echo 'Maintenance Mode Deactivated'
     ;;
esac
