#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service single
PROCESS_NAME="nginx"

if var_false "${ENABLE_NGINX}" ; then
    print_notice "Disabling Nginx Functionality"
    service_stop 10-nginx
    service_stop 11-nginx-config-reload
    rm -rf /assets/logrotate/nginx*
    rm -rf /etc/logrotate.d/nginx*
    rm -rf /assets/logrotate/nginx*
    rm -rf /etc/zabbix/*/nginx*
    rm -rf /etc/fluent-bit/conf.d/nginx*
    liftoff
    exit 0
fi

if [ ! -f "/tmp/.container/container-restart" ] ; then
    nginx_check_legacy_configuration
    nginx_configure_mode
    nginx_configure_server
    nginx_configure_authentication
    if var_true "${NGINX_ENABLE_BLOCK_BOTS}" ; then
        sed -i "/server_names_hash_bucket_size/d" /etc/nginx/nginx.conf
        nginx_configure_blockbots
    else
        sed -i "\|include /etc/nginx/snippets/bot_blocker.conf;|d" /etc/nginx/nginx.conf
    fi
    nginx_configure_logging
    nginx_configure_maintenance

    if var_true "${NGINX_ENABLE_APPLICATION_CONFIGURATION}"; then
        if [ -n "${NGINX_WEBROOT_SUFFIX}" ]; then
            _nginx_webroot_original="${NGINX_WEBROOT}"
            NGINX_WEBROOT=${NGINX_WEBROOT}${NGINX_WEBROOT_SUFFIX}
        fi
        nginx_configure_site_default

        update_template "/etc/nginx/sites.available/*.conf" \
                                                            NGINX_LISTEN_PORT \
                                                            NGINX_WEBROOT
        if [ -n "${NGINX_WEBROOT_SUFFIX}" ]; then
            NGINX_WEBROOT=${_nginx_webroot_original}
        fi

        if var_true "${NGINX_ENABLE_CREATE_SAMPLE_HTML}" ; then nginx_create_sample_html ; fi
        if silent grep -q '<WEBROOT>' /etc/nginx/sites.available/*.conf ; then
            print_notice "Detected Legacy templates in /etc/nginx/sites.avaialable. Please change '<WEBROOT>' to {{NGINX_WEBROOT}}"
            silent sed -i "s|<WEBROOT>|${NGINX_WEBROOT}|g" /etc/nginx/sites.available/*.conf
        fi
        if silent grep -q '<LISTEN_PORT>' /etc/nginx/sites.available/*.conf 2>&1 ; then
            print_notice "Detected Legacy templates in /etc/nginx/sites.avaialable. Please change '<LISTEN_PORT>' to {{NGINX_LISTEN_PORT}}"
            silent sed -i "s|<LISTEN_PORT>|${NGINX_LISTEN_PORT}|g" /etc/nginx/sites.available/*.conf
        fi

        if [ -n "${NGINX_SITE_ENABLED}" ] ; then
            if [ "${NGINX_SITE_ENABLED,,}" != "null" ] ; then
                sites=$(echo "${NGINX_SITE_ENABLED}" | tr "," "\n")
                for site in $sites; do
                    nginx_configure_site_authentication "${site}"
                    if var_true "${NGINX_ENABLE_BLOCK_BOTS}" ; then nginx_configure_site_blockbots "${site}" ; fi
                    if [ -n "${NGINX_INCLUDE_CONFIGURATION}" ] ; then nginx_configure_site_includes "${site}" ; fi
                done
            fi
        fi
    else
        print_notice "Not configurating Website configuration files"
    fi
    nginx_post_init
fi

liftoff
