#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service single
PROCESS_NAME="nginx"

if var_false "${ENABLE_NGINX}" ; then
    print_notice "Disabling Nginx Functionality"
    service_stop 10-nginx
    service_stop 11-nginx-config-reload
    rm -rf /assets/logrotate/nginx*
    rm -rf /etc/logrotate.d/nginx*
    rm -rf /assets/logrotate/nginx*
    rm -rf /etc/zabbix/*/nginx*
    rm -rf /etc/fluent-bit/conf.d/nginx*
    liftoff
    exit 0
fi

if [ ! -f "/tmp/.container/container-restart" ] ; then
    nginx_check_legacy_configuration
    nginx_configure_mode
    nginx_configure_server
    nginx_configure_authentication
    if var_true "${NGINX_ENABLE_BLOCK_BOTS}" ; then nginx_configure_blockbots ; else sed -i "\|include /etc/nginx/snippets/bot_blocker.conf;|d" /etc/nginx/nginx.conf ; fi
    nginx_configure_logging
    nginx_configure_maintenance
    if var_true "${NGINX_ENABLE_APPLICATION_CONFIGURATION}"; then
        nginx_configure_site_default
        if var_true "${NGINX_ENABLE_CREATE_SAMPLE_HTML}" ; then nginx_create_sample_html ; fi
        silent sed -i "s|<WEBROOT>|${NGINX_WEBROOT}|g" /etc/nginx/sites.available/*.conf
        silent sed -i "s|<LISTEN_PORT>|${NGINX_LISTEN_PORT}|g" /etc/nginx/sites.available/*.conf

        if [ -f "/etc/nginx/service.available/default.conf" ] ; then
            nginx_configure_site_authentication default
            if var_true "${NGINX_ENABLE_BLOCK_BOTS}" ; then nginx_configure_site_blockbots default ; fi
            if [ -n "${NGINX_INCLUDE_CONFIGURATION}" ] ; then nginx_configure_site_includes default ; fi
        fi

        if [ -n "${NGINX_SITE_ENABLED}" ] ; then
            if [ "${NGINX_SITE_ENABLED,,}" != "null" ] ; then
                sites=$(echo "${NGINX_SITE_ENABLED}" | tr "," "\n")
                for site in $sites; do
                    nginx_configure_site_authentication "${site}"
                    if var_true "${NGINX_ENABLE_BLOCK_BOTS}" ; then nginx_configure_site_blockbots "${site}" ; fi
                    if [ -n "${NGINX_INCLUDE_CONFIGURATION}" ] ; then nginx_configure_site_includes "${site}" ; fi
                done
            fi
        fi
    else
        print_notice "Not configurating Website configuration files"
    fi
    nginx_post_init
fi

liftoff
