#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="nginx"

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

liftoff

print_info "Starting nginx ${NGINX_VERSION}"
exec nginx
