#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f "/tmp/state/10-nginx" ]; then
	echo "Nginx ${NGINX_VERSION} Initializaed on "`date` >/tmp/state/10-nginx
fi

echo "** [nginx] Starting nginx ${NGINX_VERSION}"
exec nginx
