#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 10-nginx
PROCESS_NAME="nginx-config-reload"

check_container_initialized
check_service_initialized init
liftoff

while inotifywait -q -e create,delete,modify,attrib /etc/nginx/nginx.conf /etc/nginx/services.enabled /etc/nginx/snippets "${NGINX_INCLUDE_CONFIGURATION}"; do
  print_info "Reloading Nginx configuration do to a detected change"
  nginx -s reload
  exit 0
done
