#!/usr/bin/with-contenv bash


if [ ! -f /tmp/state/10-nginx ]; then
sleep 2

	### Check to see if this is a new install, if yes create directories...
	if [ ! -f /www/html/index.html ] ; then
	   echo "New Installation Detected......"
	   mkdir -p /www/html
	   touch /www/html/index.html
	   chown nginx /www/html
	fi

	### Force Reset Permissions for Security
	chown -R nginx /www/html
        mkdir -p /www/logs/nginx
        mkdir -p /www/logs/smtp
    	mkdir -p /tmp/nginx
        chown -R nginx /www/logs/nginx
        chown -R nginx /www/logs/smtp
        chown nginx /tmp/nginx
        mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** Starting nginx..'
exec nginx

